### ISSUE TITLE
Implement iOS lifecycle hooks

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/thali#136]
See #134

**Comment by yaronyg** [comment]
What work happened to make this done?

**Comment by yaronyg** [comment]
Moving these to "in progress" just so we can discuss at stand up and I can understand how they got done. Thanks!

**Comment by softwarenerd** [comment]
We are notified that the app has loaded and is ready, in JavaScript, via app.js being loaded from thali_mobile.js, which polls for JXcore being loaded. I've added two new JavaScript callbacks that are called from native code. The first is appEnteringBackground, which is called as the app is entering the background. The second is appEnteredForeground, which is called when the app becomes the foreground app.
