### ISSUE TITLE
PouchDB sends attachments even when they aren't needed during replication

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/thali#151]
When using _bulk_docs to send an update all attachments on a changed document will be included even though they haven't changed.

Similarly when downloading a changed document with a direct GET request PouchDB will include attachments=true and thus get a full copy of the attachments even though they have not changed.

This is massively increasing the cost of small document changes so we really have to fix it.

**Comment by yaronyg** [comment]
So the trick on pull replication is for us to add support for atts_since to GET requests on individual documents. Once we have done that then we can decide if we want to figure out how to make _bulk_docs not require uploading unchanged attachments.
1. Add in support for revpos
2. Add atts_since to GET - This specifically needs handling in the case that atts_since is used with open_rev and when it's not since those are two completely separate code paths in PouchDB.
3. Add use of atts_since to pull replication
4. Decide what we want to do about _bulk_docs (who also uploads attachments, even if they aren't changed, inline on all replication updates)

**Comment by MathiasVandePol** [comment]
What is the status one this one? Because i see that all my attachments are being replicated, even if the attachment itself is not changed. It should only send the stub, not?

**Comment by mohlsen** [comment]
was this fixed by https://github.com/pouchdb/pouchdb/pull/5018?

**Comment by yaronyg** [comment]
Maybe. It seems ridiculously fragile. It depends on https://github.com/pouchdb/pouchdb/pull/5018/files#diff-3b1908d46435f961119df0ed4762ec7fR12 which requires that both the source and target are using exactly the same digest algorithm with exactly the same parameters.

I would want to investigate if we can use atts_since instead as it should in theory allow us to declare to the other side which version of which attachments we have and hopefully not get them back in a pull replication. But it's been way too long since I've been neck deep in these issues to be sure. I re-read https://github.com/pouchdb/pouchdb/issues/2674#issuecomment-202939191 and I still don't understand the argument for why atts_Since doesn't fix our problem. I think the argument that Jan is making is that the way PouchDB does replication doesn't benefit from atts_since but that just argues we need to fix how PouchDB does replication.

**Comment by jo** [comment]
What do you think about [my response](https://github.com/pouchdb/pouchdb/issues/2674#issuecomment-207604358) to Jans comment? I also think _atts_since_ is the way to go.

**Comment by yaronyg** [comment]
@jo see [my original response](https://github.com/pouchdb/pouchdb/issues/2674#issuecomment-207686632). I think this approach is workable but it will require keeping track of a lot of data about the remote entity. I also haven't had time yet to really understand how PouchDB deals with state conflicts and attachments. Does it keep the conflicting attachments in different revpos?

**Comment by yaronyg** [comment]
Closed in favor of thaliproject/Thali_CordovaPlugin#1267
