### ISSUE TITLE
Define Android battery performance

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/thali#159]
How long can we have discovery turned on?
How is battery consumption affected by listening versus advertising ourselves?
How is battery consumption affected by passively listening without hearing anyone versus hearing someone and having to query them to see if they are interesting?
How much battery does synching how much data for what period of time take?
We need to start defining the battery/time consequences of our behavior so we can figure out how big a group we can handle.

**Comment by DrJukka** [comment]
Basically with Wifi direct you can not simply listen, you need to keep the interface active and to do that, you need to keep discovery active.

With nexus 4 & 5, with KitKat and Lollipop the Battery run empty in around 22 hours when there is no peers nearby. Once there are peers the Kitkat runs around 2 hours more, but Lollipop can get all the way upto 60-80 hours of Runtime.
