### ISSUE TITLE
Add Mocha test cases for thali-acl https://github.com/thaliproject/thali-acl

### ISSUE THREAD

**Issue by sreesharp** [thaliproject/thali#170]
Add Mocha test cases for thali-acl https://github.com/thaliproject/thali-acl

**Comment by yaronyg** [comment]
Why not file this issue directly on the thali-acl project? Issues should be filed on the project they are about. We can then add that project to waffle so we can track.

**Comment by sreesharp** [comment]
Sure. We can do that. Didn't understand how this waffle is working.  When I created the issue,  it went to the default project. Can we update it now? or create another issue in acl-project, and delete this one?

**Comment by yaronyg** [comment]
Beats me! Go experiment and find out! :)

**Comment by sreesharp** [comment]
This issue was moved to thaliproject/thali-acl#1
