### ISSUE TITLE
JXCore app in Apple App Store

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/thali#173]
It would be good if we can get a JXCore app successfully running in the App Store so we know Apple is happy with JXCore's approach.

**Comment by deefactorial** [comment]
@obastemur suggests that it's possible, has it been tested ?

https://github.com/jxcore/jxcore/issues/186#issuecomment-76837266

**Comment by yaronyg** [comment]
@deefactorial We should distinguish between "someone has shipped spider monkey" and "someone has shipped JXCore." Yes, I fully appreciate that one is built on the other but since Apple's decision process is a bit of a black box I would suggest that it would help if we have a more "direct" proof that Apple is o.k. with JXCore.

**Comment by yaronyg** [comment]
It shipped today! We'll see if Apple accepts it.

**Comment by obastemur** [comment]
Application is accepted on both stores see http://nubisa.com/first-node-js-application-is-accepted-to-apples-app-store/
