### ISSUE TITLE
Wifi Togling timer to refresh Wifi Direct API

### ISSUE THREAD

**Issue by DrJukka** [thaliproject/thali#197]
We would need to have a timer based solution that turns the Wifi off and back on to enable Wifi Direct Discovery to work continuously with Android devices

**Comment by yaronyg** [comment]
I'm assuming this should happen in the native code?

**Comment by yaronyg** [comment]
Note that this also need to detect if the user is currently using wifi anywhere on the device so we don't accidentally kill them. This is especially important when the device is actively in use.
