### ISSUE TITLE
Our front page sucks

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/thali#225]
Right now nobody on earth can actually understand http://www.thaliproject.org's front page. We should focus it way down. Stop talking about the vision and just focus on what we are building right now which is a Cordova plugin to enable phones to synch with each other without any Internet. As we need more functionality we'll expand the front page to capture it.

**Comment by mpodwysocki** [comment]
@deadlyfingers we could probably use this [Feeling Responsive](http://phlow.github.io/feeling-responsive/) to get started and go from there.

**Comment by yaronyg** [comment]
10/20 - Starting now he has two days and then we need him coding.

**Comment by yaronyg** [comment]
10/21 - Second day.

**Comment by yaronyg** [comment]
10/22 - Matt created the content and now David is formatting it for publishing.

**Comment by yaronyg** [comment]
10/23 - Jekyll is not picking up changes locally so that is blocking his ability to do design. David wants one more day to finish up.

**Comment by yaronyg** [comment]
10/26 - Still some UX glitches that have to be worked out. PR should be out today.

**Comment by deadlyfingers** [comment]
Didn't grab existing Thali pages/posts when using git merge with 'gh-pages' branch... So copied them over for testing. Are we best replacing this branch?

**Comment by yaronyg** [comment]
10/27 - The merge with our existing site went bad. Will need to figure that out.

**Comment by deadlyfingers** [comment]
Easiest option was to copy in old markdown files...

Thali connectivity idea:
![thali-wifi](https://cloud.githubusercontent.com/assets/1880480/10798305/efc434a0-7d9e-11e5-83f9-695694cf2823.png)

Thali tech dish idea:
![thali7-pacific-blue](https://cloud.githubusercontent.com/assets/1880480/10787606/26a41448-7d6a-11e5-80b2-bbb4d4a40179.png)

Thali dish logo:
![thali-dish-logo](https://cloud.githubusercontent.com/assets/1880480/10790382/f4ba42f2-7d7a-11e5-8767-5257aba8f469.png)

Thali dish logos (asymmetrical):
![thali-dish-logos](https://cloud.githubusercontent.com/assets/1880480/10842493/ebe804dc-7ee9-11e5-9495-eee0ee35b787.png)

Thali dish icon logo (asymmetrical):
![thali-dish-logo](https://cloud.githubusercontent.com/assets/1880480/10797888/b2149548-7d9c-11e5-84bd-8739b8ea8d08.png)

**Comment by yaronyg** [comment]
10/28 - It refuses to die! Just one more day, he promises.

**Comment by deadlyfingers** [comment]
New banner design:
![banner](https://cloud.githubusercontent.com/assets/1880480/10802039/40c9465c-7db2-11e5-9e86-e42e7c1658df.png)

**Comment by yaronyg** [comment]
SCORE!

**Comment by deadlyfingers** [comment]
Do we have a Google Analytics ID?
Also just wondering - is there a mail/tweet tool running that fires blog posts once they get added into the 'gh-pages' branch? If so we might need to disarm this when we merge as they will all be added in as 'new' posts again...

**Comment by yaronyg** [comment]
We do not have a google Analytics ID. Do you want to set one up? We use twitter feed, contact me separately and I'll give you our account name and password.

**Comment by deadlyfingers** [comment]
Should we enable a breadcrumb structure? It would be nice to support Jekyll breadcrumb links but that would break any external links to pages...
eg.
http://thaliproject.org/nodeondevices/
would become:
http://thaliproject.org/TechnologyInvestigations/NodeOnDevices/
this structure would allow for traversing back to related content...

**Comment by deadlyfingers** [comment]
![draft](https://cloud.githubusercontent.com/assets/1880480/10821287/8ab8554a-7e49-11e5-8822-b45336ed0f1f.jpg)

Just have to decide on content for 3 box images / text...
1. Maybe use "No Internet.. No problem" as tagline in place of local p2p

**Comment by mattpodwysocki** [comment]
@deadlyfingers no internet no problem is a great tagline unless you want to put it directly on the Thali logo itself up above

**Comment by deadlyfingers** [comment]
Just testing - then we should be ready for PR!
