### ISSUE TITLE
Please fix our icons on GitHub and Twitter

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/thali#232]
https://github.com/thaliproject

Thanks for updating Twitter but can you please make our picture the one with the words in it instead of the empty one? The empty feels a bit..weird. I completely understand if David hadn't given us a stand alone "filled thali". If so please assign him a bug to produce it and then we can use that.

**Comment by deadlyfingers** [comment]
Added more logos SVG to the archive:
https://onedrive.live.com/redir?resid=C04BD5A39247EDB0!75130&authkey=!AKt6TjzDPfmVhPg&ithint=file%2czip
