### ISSUE TITLE
Why don't lists render properly on our website?

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/thali#253]
http://thaliproject.org/Info/ scroll down to How? and notice that none of the bulleted lists are rendering as bulleted lists. What's going on?

**Comment by deadlyfingers** [comment]
Will have a look at the markdown - any other pages doing this?

**Comment by deadlyfingers** [comment]
Related issue: 
https://github.com/jekyll/jekyll/issues/2139

Adding redcarpet `"lax_spacing"` extension to __config.xml_ seems to fix this - will submit a PR after checking other pages for potential side effects...

**Comment by deadlyfingers** [comment]
Submitted PR

**Comment by deadlyfingers** [comment]
NB: Headlines require a space after '#' character with kramdown.
