### ISSUE TITLE
Some documentation links don't work

### ISSUE THREAD

**Issue by juhanak** [thaliproject/thali#254]
https://github.com/thaliproject/thali/blob/gh-pages/pages/documentation/DeveloperHandbook.md

> The first thing to do is read. Please start here. You can probably skip most of the links except for this one and this one which will drive all of our immediate work. With these three articles you should have the background you need to understand what we are up to.

Links in this chapter are dead. Apparently the document structure has changed and links are not updated accordingly. Same here: 

https://github.com/thaliproject/thali/blob/76ce18b32a1a986eeb8a52fff28805fe08b7f4c5/pages/architecture/ThaliAndIoT.md

>  As previously mentioned a key decision made in...

**Comment by yaronyg** [comment]
These will now work on http://www.thaliproject.org
