### ISSUE TITLE
Replacing redcarpet with kramdown

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/thali#257]
https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0 explains that GitHub pages is moving from redcarpet to Kramdown and is making some other changes. We currently specify the use of redcarpet. Can you please review the article I linked to above and figure out what changes we need to make on our website?

**Comment by deadlyfingers** [comment]
Just tried the switch from redcarpet locally, but kramdown doesn't have the same config extensions...
Have to see if I can get toc and strikethrough working under kramdown

Issues:
https://github.com/gettalong/kramdown/issues/130

I can do this with Javascript regex on the body

```
// add strikethrough to md text
  function strikethrough(){
    document.body.innerHTML = document.body.innerHTML.replace(
      /\~\~(.+)\~\~/gim,
      '<del>$1</del>'
    );
  }
```

**Comment by deadlyfingers** [comment]
Submitted to PR - https://github.com/thaliproject/thali/pull/258
