### ISSUE TITLE
update TCP/IP section of PresenceProtocolBindings.md

### ISSUE THREAD

**Issue by baydet** [thaliproject/thali#277]
We haven't properly described Browser's behavior during TCP/IP binding. Details [here](https://github.com/thaliproject/Thali_CordovaPlugin/issues/1052)

**Comment by yaronyg** [comment]
@baydet After our discussion I thought we said that the spec is correct? If so then please just close this bug. If not then please send me a note explaining what is still wrong.

**Comment by baydet** [comment]
Specs are clear. Closing issue
