### ISSUE TITLE
Get HTML5 Environment working smoothly

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/thali#6]
Right now our demo author is blocked because it's just too hard to get the HTML5 environment working. What we need is the following:
1. An APK and distZip version of the TDH that one can just run
2. A distZip of the seed that one can run and pass in a directory containing HTML5 to and in return get as output an APK and distZip for the app.

**Comment by timfpark** [comment]
To be clear, I'm not blocked, but I think nearly all devs trying the platform will abandon if they can't get the platform up in running under an hour, and hence we need to get a better bootstrap story before we even think about tackling a demo.

**Comment by yaronyg** [comment]
It's vastly easier now! And Tim did manage to get up and running. We will do even better for the dev preview.
