### ISSUE TITLE
Get PouchDB to TDH Replication Working

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/thali#8]
We already have tests for this but they are using the old web framework. So what we need to do is move these tests over to the new framework. I suspect we will need to write some code that implements our own 'poor man's' continuous replication because of issues we've seen in CouchBase. This would just be a library to repeatedly do one off replications between PouchDB and the TDH. There is another work item here to get a quick little library (just a single XHR call) from PouchDB asking the TDH to do a replication on PouchDB's behalf. Ideally this would just call the replication manager.

**Comment by judell** [comment]
Here's how we did it in the old framework for the PPNet demo:

```
var syncFromRemote = function() {
  // do this until/unless couchbase lite supports continuous sync
db.replicate.from(remote, {
    complete: function(err,resp) {
              if (err)
                  console.log(err);
              else
                  if ( resp.docs_read > 0 )
                      console.log('synced ' + resp.docs_read);
              syncFromRemote();                 
          }
});
```

   }

   syncFromRemote();

**Comment by yaronyg** [comment]
Working!
