### ISSUE TITLE
Wi-Fi-Direct on Android, testing data

### ISSUE THREAD

**Issue by DrJukka** [thaliproject/thali#86]
he issues and workarounds for Android Wi-Fi-Direct were investigated in the [previous blog article](http://www.drjukka.com/blog/wordpress/?p=24). With this article we did measure timings between different operations to get idea on where the time is spend, and how much time it does take to get data through the connection.

Read the results from the [blog article](http://www.drjukka.com/blog/wordpress/?p=29)

**Comment by yaronyg** [comment]
Jukka, when you post the blog article it would perhaps be best if it had some context for the reader. Why were you investigating Wi-Fi Direct? What was the goal? Remember, the folks reading the article don't have any context!
