### ISSUE TITLE
Figure out which OpenSSL APIs we need

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/thali#98]
We need to use OpenSSL to enable us to:
- Generate Public/Private RSA keys of 4K size
- Generate X.509 certs for a key
- Store the public/private key pair as a PKCS12 file
- Parsing X.509 certs to determine their validity

**Comment by srichal** [comment]
Was able to generate the RSA key by calling the existing API "RSA_generate_key_ex()" in JXcore. Did this in the Android application that is linked to the JXcore build.

But wanted to call the API in a stand alone CPP source file. This is the needed to test the existing OpenSSL APIs as well as new ones independent of the platform.

Wrote the CPP source file as well as the make file to link to the JXcore build. But came across linking errors. Pinged Oguz (Nubisa) and he provided clues on updating my make file.

Will try to fix all the errors and thus complete the first requirement of this task.

**Comment by srichal** [comment]
Fixed most of the link errors but was left with three system errors. Chatted with Ogus this morning. Turns out that we cannot do this as of now but he will work on adding this feature soon.

Went back to using the Android app to complete the first requirement. Currently working on writing the generated RSA key to a file.

**Comment by srichal** [comment]
As writing/running C code in an Android app is slow, Yaron suggested to complete this task by using pure OpenSSL library.

Cloned and built the OpenSSL library and created a desktop C source file to complete the first part of this task.

Will work on generating the X.509 certificate next.

**Comment by srichal** [comment]
Should be able to complete all the four steps by this Thursday (26th) (end of this week at the latest).

**Comment by srichal** [comment]
• Generate Public/Private RSA keys of 4K size (done – was able to verify key-size using command line and was also able to save as privateKey.pem & publicKey.pem files)
• Generate X.509 certs for a key (done – was able to generate a self-signed cert and also save it as cert.pem file)
• Store the public/private key pair as a PKCS12 file (will do this today)
• Parsing X.509 certs to determine their validity (done - used two different openssl APIs to verify that my cert is good and was able to verify using command line)

**Comment by srichal** [comment]
Completed the creation of the PKCS12 file by combining the private key and the certificate. Tested this by parsing the PKCS12 file and extracting the same private key and certificate.

**Comment by srichal** [comment]
Committed the C API to the Thali github (https://github.com/thaliproject/openssl-c-api-for-thali).
